"""Builds the TradingView Pine v5 scripts for the FX-Agents setups (python pine/build.py).

Each script = header + the setup's own signal code + the bot's shared trade management, so every script
manages trades the same way the bot does (1R partial + trailing runner, or a fixed TP, NY entry windows,
15:50 flatten, max hold, the 1h trend filter standing in for the bot's bias rule). Bands, EMAs and
higher-timeframe values only use CLOSED candles, so nothing repaints.
"""
from pathlib import Path

HERE = Path(__file__).parent

HEAD = '''//@version=5
// FX-Agents · {title}
// {about}
// Generated by pine/build.py from the bot's rules. Set Properties → Commission/Slippage to your broker's spread.
strategy("FX-Agents · {title}", overlay=true, initial_capital=100000, default_qty_type=strategy.fixed,
     default_qty_value=1, process_orders_on_close=true, margin_long=0, margin_short=0)
'''

COMMON_INPUTS = '''
// ── the bot's trade management inputs ────────────────────────────────────────────────────────
exitMode   = input.string("Bot (1R partial + trail)", "Exit", options=["Bot (1R partial + trail)", "Fixed TP"], group="Management")
rr         = input.float({rr}, "First target / TP (R)", step=0.25, group="Management")
partialPct = input.float(50, "Bank at first target (%)", group="Management")
lockR      = input.float(0.1, "Stop after first target (+R)", group="Management")
trailStep  = input.float(1.0, "Trail step (R)", group="Management")
maxHoldMin = input.int({hold}, "Max hold (minutes)", group="Management")
windows    = input.string("{windows}", "Entry windows (New York)", group="Management")
flatHm     = input.int(1550, "Flatten at (HHMM, New York)", group="Management")
useBias    = input.bool(true, "Only with the 1h trend (EMA20/50 on closed 1h bars)", group="Management")

nyHm  = hour(time, "America/New_York") * 100 + minute(time, "America/New_York")
inWin = not na(time(timeframe.period, windows, "America/New_York")) and not (nyHm >= flatHm - 20 and nyHm < 1700)
htfC  = request.security(syminfo.tickerid, "60", close[1], lookahead=barmerge.lookahead_on)
htfF  = request.security(syminfo.tickerid, "60", ta.ema(close, 20)[1], lookahead=barmerge.lookahead_on)
htfS  = request.security(syminfo.tickerid, "60", ta.ema(close, 50)[1], lookahead=barmerge.lookahead_on)
biasUp = not useBias or (htfF > htfS and htfC > htfS)
biasDn = not useBias or (htfF < htfS and htfC < htfS)
atr14 = ta.atr(14)

var float eP = na
var float rP = na
var float stopNow = na
var int   stepN = 0
var int   entryTime = na
goLong = false
goShort = false
stopL = float(na)
stopS = float(na)
'''

FOOTER = '''
// ── entries & the bot's management ────────────────────────────────────────────────────────────
flat = strategy.position_size == 0
if flat and inWin and goLong and biasUp and not na(stopL) and close > stopL
    eP := close
    rP := close - stopL
    stopNow := stopL
    stepN := 0
    entryTime := time
    strategy.entry("L", strategy.long)
else if flat and inWin and goShort and biasDn and not na(stopS) and close < stopS
    eP := close
    rP := stopS - close
    stopNow := stopS
    stepN := 0
    entryTime := time
    strategy.entry("S", strategy.short)

dir = strategy.position_size > 0 ? 1 : strategy.position_size < 0 ? -1 : 0
if dir != 0 and exitMode == "Bot (1R partial + trail)"
    best = dir > 0 ? high : low
    while (best - (eP + dir * (rr + stepN * trailStep) * rP)) * dir >= 0 and stepN < 50
        stepN += 1
        newStop = stepN == 1 ? eP + dir * lockR * rP : eP + dir * (rr + (stepN - 2) * trailStep) * rP
        if (newStop - stopNow) * dir > 0
            stopNow := newStop

if exitMode == "Fixed TP"
    strategy.exit("TP L", "L", limit=eP + rr * rP, stop=stopNow)
    strategy.exit("TP S", "S", limit=eP - rr * rP, stop=stopNow)
else
    strategy.exit("Partial L", "L", qty_percent=partialPct, limit=eP + rr * rP, stop=stopNow)
    strategy.exit("Runner L", "L", stop=stopNow)
    strategy.exit("Partial S", "S", qty_percent=partialPct, limit=eP - rr * rP, stop=stopNow)
    strategy.exit("Runner S", "S", stop=stopNow)

if dir != 0 and not na(entryTime) and time - entryTime >= maxHoldMin * 60000
    strategy.close_all("max hold")
if nyHm >= flatHm and nyHm < 1700
    strategy.close_all("15:50 flatten")
plot(dir != 0 ? stopNow : na, "Stop", color.new(color.red, 0), style=plot.style_linebr)
'''

BOT_WINDOWS = "0200-0500,0830-1130,1330-1530,2000-2359"

SCRIPTS = {
    "trend_pullback": dict(
        title="Trend pullback", rr=1.0, hold=240, windows=BOT_WINDOWS,
        about="With the 1h trend, buy the first dip to the chart EMA that closes back above it, bullish (mirror for shorts). Use 15m–1h charts.",
        code='''
emaLen   = input.int(20, "Pullback EMA", group="Setup")
swingN   = input.int(5, "Stop below the lowest low of N bars", group="Setup")
bufAtr   = input.float(0.2, "Stop buffer (ATR)", group="Setup")
e   = ta.ema(close, emaLen)
e50 = ta.ema(close, 50)
goLong  := e > e50 and low[1] > e[1] and low <= e and close > e and close > open
goShort := e < e50 and high[1] < e[1] and high >= e and close < e and close < open
stopL := ta.lowest(low, swingN) - bufAtr * atr14
stopS := ta.highest(high, swingN) + bufAtr * atr14
plot(e, "Pullback EMA", color.new(color.blue, 0))
'''),
    "trend_breakout": dict(
        title="Trend breakout", rr=1.0, hold=240, windows=BOT_WINDOWS,
        about="With the 1h trend, buy a close above the previous N bars' high while price is above a rising EMA50 (mirror for shorts). Use 15m–1h charts.",
        code='''
n       = input.int(20, "Breakout of the previous N bars", group="Setup")
stopAtr = input.float(1.5, "Stop (ATR)", group="Setup")
e50 = ta.ema(close, 50)
hh  = ta.highest(high, n)[1]
ll  = ta.lowest(low, n)[1]
var int lastL = na
var int lastS = na
goLong  := close > hh and close > e50 and e50 > e50[5] and (na(lastL) or bar_index - lastL >= n)
goShort := close < ll and close < e50 and e50 < e50[5] and (na(lastS) or bar_index - lastS >= n)
if goLong
    lastL := bar_index
if goShort
    lastS := bar_index
stopL := close - stopAtr * atr14
stopS := close + stopAtr * atr14
'''),
    "london_breakout": dict(
        title="London breakout (Asian range)", rr=1.0, hold=240, windows="0200-0500",
        about="Asian box 20:00→03:00 NY; first close outside it with a body ≥0.5 ATR before 08:00 NY; stop 1.5 ATR beyond the breakout candle. Gold, 3m–15m charts.",
        code='''
boxEnd  = input.int(3, "Box ends at (hour, NY)", group="Setup")
until   = input.int(8, "Breakouts until (hour, NY)", group="Setup")
minBody = input.float(0.5, "Breakout body ≥ (ATR)", group="Setup")
stopAtr = input.float(1.5, "Stop beyond the breakout candle (ATR)", group="Setup")
nyH = hour(time, "America/New_York")
inBox = nyH >= 20 or nyH < boxEnd
var float bHi = na
var float bLo = na
var bool doneL = false
var bool doneS = false
if nyH == 20 and nyH[1] != 20
    bHi := high
    bLo := low
    doneL := false
    doneS := false
else if inBox
    bHi := na(bHi) ? high : math.max(bHi, high)
    bLo := na(bLo) ? low : math.min(bLo, low)
canBreak = not inBox and nyH >= boxEnd and nyH < until and not na(bHi)
goLong  := canBreak and not doneL and close > bHi and close - open >= minBody * atr14
goShort := canBreak and not doneS and close < bLo and open - close >= minBody * atr14
if goLong
    doneL := true
if goShort
    doneS := true
stopL := low - stopAtr * atr14
stopS := high + stopAtr * atr14
plot(bHi, "Asian high", color.new(color.green, 30), style=plot.style_linebr)
plot(bLo, "Asian low", color.new(color.red, 30), style=plot.style_linebr)
'''),
    "rsi_pullback": dict(
        title="RSI pullback", rr=1.0, hold=240, windows=BOT_WINDOWS,
        about="With the EMA200 trend, buy when RSI(14) recovers above 35 (sell when it rolls below 65); stop beyond the recent swing. Best on gold 15m in the year test.",
        code='''
lo      = input.int(35, "RSI pullback level", group="Setup")
swingN  = input.int(6, "Stop beyond the swing of N bars", group="Setup")
bufAtr  = input.float(0.15, "Stop buffer (ATR)", group="Setup")
useTrend = input.bool(true, "Only with the EMA200 trend", group="Setup")
r    = ta.rsi(close, 14)
e200 = ta.ema(close, 200)
goLong  := ta.crossover(r, lo) and (close > e200 or not useTrend)
goShort := ta.crossunder(r, 100 - lo) and (close < e200 or not useTrend)
stopL := ta.lowest(low, swingN + 1) - bufAtr * atr14
stopS := ta.highest(high, swingN + 1) + bufAtr * atr14
'''),
}


def build() -> list[str]:
    out = []
    for name, d in SCRIPTS.items():
        txt = HEAD.format(title=d["title"], about=d["about"]) + COMMON_INPUTS.format(rr=d["rr"], hold=d["hold"], windows=d["windows"]) \
            + d["code"] + FOOTER
        (HERE / f"{name}.pine").write_text(txt)
        out.append(name)
    return out


if __name__ == "__main__":
    print("wrote", ", ".join(build()))
